/** Every MCP tool name — one per AureonClient SDK method. */
export const SDK_TOOL_NAMES = [
  "aureon_ping",
  "aureon_get_overview",
  "aureon_get_portfolio",
  "aureon_list_objectives",
  "aureon_get_objective",
  "aureon_get_health",
  "aureon_list_timeline",
  "aureon_list_market_presets",
  "aureon_get_restore_plan",
  "aureon_run_execution",
  "aureon_restore_objective",
  "aureon_list_executions",
  "aureon_get_vault",
  "aureon_get_vault_status",
  "aureon_prepare_vault_deposit",
  "aureon_prepare_vault_withdraw",
  "aureon_get_auth_nonce",
  "aureon_verify_wallet",
  "aureon_dev_login",
  "aureon_logout",
  "aureon_me",
  "aureon_create_objective",
  "aureon_update_objective",
  "aureon_pause_objective",
  "aureon_resume_objective",
  "aureon_set_portfolio",
  "aureon_clear_portfolio",
  "aureon_sync_portfolio",
  "aureon_apply_market_event",
  "aureon_refresh_watchdog",
  "aureon_list_api_keys",
  "aureon_create_api_key",
  "aureon_revoke_api_key",
  "aureon_toggle_api_key",
  "aureon_registry_status",
  "aureon_get_objective_registry",
  "aureon_prepare_objective_registry",
] as const;

export const TOOL_COUNT = SDK_TOOL_NAMES.length;
